import type { Session, Progress } from './types';
export type ReadingStore = { listSessions(): Promise<Session[]>; saveSession(s: Session): Promise<void>; getProgress(bookId: string): Promise<Progress | undefined>; saveProgress(p: Progress): Promise<void> };
export const STORAGE_NOTICE = 'reading-storage-notice';
function warn() { if (typeof window !== 'undefined') window.dispatchEvent(new CustomEvent(STORAGE_NOTICE)); }
function validSession(s: Session) { return s && typeof s.id === 'string' && typeof s.bookId === 'string' && Number.isFinite(s.startedAt) && Number.isFinite(s.lastActivityAt) && Array.isArray(s.visits) && s.visits.every(v => Number.isInteger(v.page) && v.page >= 0 && v.page < 6 && Number.isFinite(v.at) && typeof v.localDate === 'string') && Array.isArray(s.intervals) && s.intervals.every(i => Number.isFinite(i.startMs) && Number.isFinite(i.endMs) && i.endMs >= i.startMs && typeof i.localDate === 'string') && (s.completedAt === null || Number.isFinite(s.completedAt)); }
export async function openReadingStore(): Promise<ReadingStore> {
    const db = await new Promise<IDBDatabase>((resolve, reject) => { const req = indexedDB.open('little-reading-house', 1); req.onupgradeneeded = () => { const db = req.result; db.createObjectStore('sessions', { keyPath: 'id' }); db.createObjectStore('progress', { keyPath: 'bookId' }); }; req.onsuccess = () => resolve(req.result); req.onerror = () => reject(req.error); req.onblocked = () => reject(new Error('请关闭其他旧版本窗口后重试')); });
    db.onversionchange = () => db.close();
    function read<T>(name: string, key?: string): Promise<T> { return new Promise((resolve, reject) => { const tx = db.transaction(name); const request = key === undefined ? tx.objectStore(name).getAll() : tx.objectStore(name).get(key); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); }); }
    function write(name: string, value: Session | Progress): Promise<void> { return new Promise((resolve, reject) => { const tx = db.transaction(name, 'readwrite'); const store = tx.objectStore(name); if (name === 'progress') { const p = value as Progress; const req = store.get(p.bookId); req.onsuccess = () => { if (!req.result || req.result.updatedAt <= p.updatedAt) store.put(p); }; } else store.put(value); tx.oncomplete = () => { if (typeof window !== 'undefined') window.dispatchEvent(new Event('reading-updated')); resolve(); }; tx.onerror = () => reject(tx.error); tx.onabort = () => reject(tx.error); }); }
    return { async listSessions() { const rows = await read<Session[]>('sessions'); const valid = rows.filter(validSession); if (valid.length !== rows.length) warn(); return valid; }, saveSession: s => write('sessions', s), async getProgress(id) { const p = await read<Progress | undefined>('progress', id); if (p && (!Number.isInteger(p.page) || p.page < 0 || p.page > 5 || typeof p.completed !== 'boolean' || !Number.isFinite(p.updatedAt))) { warn(); return undefined; } return p; }, saveProgress: p => write('progress', p) };
}
