import type { Book } from './types';
import b0 from './books/my-animals.json';
import b1 from './books/colors-around-me.json';
import b2 from './books/my-toys.json';
import b3 from './books/fruit-time.json';
import b4 from './books/my-family.json';
import b5 from './books/little-clothes.json';
import b6 from './books/my-face.json';
import b7 from './books/on-the-farm.json';
import b8 from './books/i-can-move.json';
import b9 from './books/i-see-colors.json';
import b10 from './books/a-little-seed.json';
import b11 from './books/where-is-bear.json';
import b12 from './books/my-morning.json';
import b13 from './books/lets-make-a-snack.json';
import b14 from './books/a-rainy-day.json';
import b15 from './books/time-for-bed.json';
export const books = [b0, b1, b2, b3, b4, b5, b6, b7, b8, b9, b10, b11, b12, b13, b14, b15] as Book[];
export const getBook = (id: string) => books.find(book => book.id === id);
