import json
from pathlib import Path
root=Path(__file__).resolve().parents[1]
# Editorial source: English, Chinese, and image direction stay paired.
rows=[
('my-animals','aa','My Animals','我的动物朋友','#eac584',[
('A cat.','一只猫。','A single adorable orange kitten with cream muzzle sits on a turquoise rug in a cozy playroom.'),
('A dog.','一只狗。','A friendly golden puppy sits on a turquoise rug in a cozy playroom.'),
('A rabbit.','一只兔子。','A fluffy white rabbit with pink ears sits on a turquoise rug in a cozy playroom.'),
('A bird.','一只小鸟。','A cheerful small blue bird perches on a low wooden stand in a cozy playroom.'),
('A fish.','一条鱼。','One bright orange goldfish swims in a clear rounded aquarium with a tiny green plant.'),
('A turtle.','一只乌龟。','A friendly little green turtle stands beside a smooth stone in a cozy playroom.')]),
('colors-around-me','aa','Colors Around Me','身边的颜色','#f0b8a0',[
('A red ball.','一个红色的球。','One glossy red ball on a light wooden playroom floor.'),('A blue car.','一辆蓝色的车。','One bright blue toy car on a light wooden playroom floor.'),('A yellow duck.','一只黄色的鸭子。','One cheerful yellow rubber duck on a light wooden playroom floor.'),('A green leaf.','一片绿色的叶子。','One fresh vivid green leaf resting on a pale wooden table.'),('A pink flower.','一朵粉色的花。','One pink flower growing in a small terracotta pot on a pale table.'),('An orange cup.','一个橙色的杯子。','One clearly orange cup with a rounded handle on a pale wooden table.')]),
('my-toys','aa','My Toys','我的玩具箱','#a8cdd6',[
('My teddy bear.','我的泰迪熊。','One plush honey brown teddy bear with a teal bow sits in a cozy nursery.'),('My ball.','我的球。','One large colorful beach ball rests in a cozy nursery.'),('My blocks.','我的积木。','A small stack of colorful wooden building blocks in a cozy nursery, no letters.'),('My train.','我的小火车。','A red wooden toy train with two little carriages on a simple track.'),('My kite.','我的风筝。','A bright diamond-shaped kite with ribbon bows leaning in a cozy nursery.'),('My doll.','我的玩偶。','A friendly cloth doll in yellow overalls sits in a cozy nursery.')]),
('fruit-time','aa','Fruit Time','水果时间','#e8b270',[
('An apple.','一个苹果。','One shiny red apple with a small green leaf on a kitchen table.'),('A banana.','一根香蕉。','One ripe yellow banana on a kitchen table.'),('An orange.','一个橙子。','One round orange fruit with dimpled peel and green leaf on a kitchen table.'),('A pear.','一个梨。','One pale green pear on a kitchen table.'),('Some grapes.','一些葡萄。','A small bunch of purple grapes on a kitchen table.'),('A watermelon.','一个西瓜。','One green striped watermelon and a red juicy slice on a kitchen table.')]),
('my-family','aa','My Family','温暖的家','#e2b9bd',[
('My mom.','我的妈妈。','A kind mother with short black bob hair and coral cardigan waves in a warm family living room.'),('My dad.','我的爸爸。','A kind father with short black hair and blue shirt waves in a warm family living room.'),('My sister.','我的姐姐。','A cheerful girl with black pigtails wearing yellow overalls stands in a warm family living room.'),('My brother.','我的弟弟。','A cheerful little boy with short black hair wearing green overalls stands in a warm family living room.'),('My grandma.','我的奶奶。','A smiling grandmother with gray bob hair and lavender cardigan sits in a warm family living room.'),('My grandpa.','我的爷爷。','A smiling grandfather with gray hair and brown cardigan sits in a warm family living room.')]),
('little-clothes','aa','Little Clothes','穿好小衣服','#bfc6d9',[
('My hat.','我的帽子。','One small yellow sunhat on a round nursery stool.'),('My shirt.','我的上衣。','One small teal shirt on a wooden hanger against a warm nursery wall.'),('My pants.','我的裤子。','One pair of small blue pants neatly laid on a nursery stool.'),('My socks.','我的袜子。','One pair of small coral striped socks on a nursery stool.'),('My shoes.','我的鞋子。','One pair of cheerful yellow child shoes on a nursery floor.'),('My coat.','我的外套。','One small coral coat hanging on a wooden nursery peg.')]),
('my-face','aa','My Face','认识小脸蛋','#e5cda0',[
('My eyes.','我的眼睛。','Close portrait of a cheerful preschool girl with black bob hair and yellow shirt, pointing gently below both open eyes.'),('My ears.','我的耳朵。','Close portrait of a cheerful preschool girl with black bob hair and yellow shirt, pointing to her two ears.'),('My nose.','我的鼻子。','Close portrait of a cheerful preschool girl with black bob hair and yellow shirt, pointing to the tip of her nose.'),('My mouth.','我的嘴巴。','Close portrait of a cheerful preschool girl with black bob hair and yellow shirt, pointing beside her smiling mouth.'),('My hair.','我的头发。','Close portrait of a cheerful preschool girl with black bob hair and yellow shirt, gently touching the top of her hair.'),('My face.','我的脸。','Close portrait of a cheerful preschool girl with black bob hair and yellow shirt, smiling with both hands framing her cheeks.')]),
('on-the-farm','aa','On the Farm','农场的一天','#b7ce9b',[
('A cow.','一头奶牛。','One friendly black and white cow on a sunny farm with a distant red barn.'),('A pig.','一只猪。','One friendly pink pig on a sunny farm with a distant red barn.'),('A sheep.','一只绵羊。','One fluffy white sheep on a sunny farm with a distant red barn.'),('A horse.','一匹马。','One gentle brown horse on a sunny farm with a distant red barn.'),('A hen.','一只母鸡。','One cheerful brown hen on a sunny farm with a distant red barn.'),('A goat.','一只山羊。','One friendly little white goat with small horns on a sunny farm with a distant red barn.')]),
('i-can-move','A','I Can Move','动起来吧','#efbd86',[
('I can walk.','我会走路。','A preschool child with short black hair, teal overalls and cream shirt walks along a sunny garden path.'),('I can run.','我会跑步。','The same preschool child with short black hair, teal overalls and cream shirt runs across a sunny garden.'),('I can jump.','我会跳。','The same preschool child with short black hair, teal overalls and cream shirt jumps joyfully with both feet visibly off the grass.'),('I can hop.','我会单脚跳。','The same preschool child with short black hair, teal overalls and cream shirt hops on one foot, other knee lifted.'),('I can dance.','我会跳舞。','The same preschool child with short black hair, teal overalls and cream shirt dances with arms out in a sunny garden.'),('I can rest.','我会休息。','The same preschool child with short black hair, teal overalls and cream shirt rests sitting under a tree.')]),
('i-see-colors','A','I See Colors','发现彩色世界','#abcfc2',[
('I see a yellow duck.','我看到一只黄色的鸭子。','A preschool girl in coral dress observes one yellow duck at a little garden pond.'),('I see a red flower.','我看到一朵红色的花。','A preschool girl in coral dress observes one vivid red flower in a garden.'),('I see a blue butterfly.','我看到一只蓝色的蝴蝶。','A preschool girl in coral dress watches a large blue butterfly near her hand.'),('I see a green frog.','我看到一只绿色的青蛙。','A preschool girl in coral dress observes one green frog on a lily pad.'),('I see a purple kite.','我看到一只紫色的风筝。','A preschool girl in coral dress looks at a clearly purple kite in the blue sky.'),('I see an orange fish.','我看到一条橙色的鱼。','A preschool girl in coral dress observes one orange fish swimming in a clear garden pond.')]),
('a-little-seed','A','A Little Seed','一颗小种子','#c4d29b',[
('I have a little seed.','我有一颗小种子。','A preschool child in yellow overalls shows a single brown seed on an open palm beside an empty terracotta pot.'),('I put it in the soil.','我把它放进土里。','A preschool child in yellow overalls places a brown seed into soil in a terracotta pot.'),('I water my little seed.','我给我的小种子浇水。','A preschool child in yellow overalls carefully waters soil in a terracotta pot with a small green watering can.'),('The sun warms the soil.','阳光温暖着泥土。','A terracotta pot filled with moist soil stands on a sunny windowsill with warm sun rays.'),('A little plant comes up.','一株小苗长出来了。','A tiny bright green two-leaf sprout emerges from soil in a terracotta pot on a sunny windowsill.'),('My plant has a flower.','我的植物开花了。','A preschool child in yellow overalls admires one yellow flower on a green plant in the same terracotta pot.')]),
('where-is-bear','A','Where Is Bear?','小熊在哪里','#c6bddb',[
('Bear is on the bed.','小熊在床上。','A honey brown teddy bear with a teal bow sits clearly ON TOP of a small wooden bed with cream quilt.'),('Bear is under the chair.','小熊在椅子下面。','A honey brown teddy bear with a teal bow sits clearly UNDER a small wooden chair, chair seat directly above bear.'),('Bear is in the box.','小熊在盒子里。','A honey brown teddy bear with a teal bow sits INSIDE an open coral toy box, its head visible above the rim.'),('Bear is behind the door.','小熊在门后面。','A honey brown teddy bear with a teal bow peeks from BEHIND a partly open mint bedroom door.'),('Bear is beside the lamp.','小熊在台灯旁边。','A honey brown teddy bear with a teal bow sits BESIDE a small rounded yellow lamp on a safe low table.'),('Bear is with me.','小熊和我在一起。','A preschool child in yellow pajamas warmly hugs a honey brown teddy bear with a teal bow.')]),
('my-morning','A','My Morning','早安，小朋友','#efc9a0',[
('I wake up.','我醒来了。','A preschool child with black bob hair in yellow pajamas wakes in a small wooden bed with cream quilt.'),('I wash my face.','我洗脸。','A preschool child with black bob hair in yellow pajamas washes face at a low bathroom sink.'),('I brush my teeth.','我刷牙。','A preschool child with black bob hair in yellow pajamas brushes teeth with a small teal toothbrush.'),('I put on my shirt.','我穿上上衣。','A preschool child with black bob hair puts on a coral shirt in a cozy bedroom.'),('I eat my breakfast.','我吃早餐。','A preschool child with black bob hair wearing a coral shirt eats toast and fruit at a kitchen table.'),('I am ready to play.','我准备好玩耍啦。','A preschool child with black bob hair wearing a coral shirt and teal pants waves in a sunny garden.')]),
('lets-make-a-snack','A',"Let's Make a Snack",'一起做点心','#deb6a0',[
('I wash my hands.','我洗手。','A preschool child in mint apron washes hands with soap at a low kitchen sink.'),('I get a little bowl.','我拿来一个小碗。','A preschool child in mint apron places an empty yellow bowl on a kitchen table.'),('I put fruit in a bowl.','我把水果放进碗里。','A preschool child in mint apron puts banana slices and berries in a yellow bowl.'),('I add some yogurt.','我加一些酸奶。','A preschool child in mint apron pours a little white yogurt from a small jug into a yellow bowl of fruit.'),('I mix it with a spoon.','我用勺子搅拌。','A preschool child in mint apron mixes fruit and yogurt in a yellow bowl with a spoon.'),('I share my yummy snack.','我分享美味的点心。','A preschool child in mint apron shares two yellow bowls of fruit yogurt with a friend at a kitchen table.')]),
('a-rainy-day','A','A Rainy Day','下雨也快乐','#adcad9',[
('I see the rain.','我看到下雨了。','A preschool child with short black hair wearing a yellow raincoat watches raindrops through a window.'),('I put on my boots.','我穿上雨靴。','A preschool child with short black hair wearing a yellow raincoat pulls on bright red rain boots.'),('I take my umbrella.','我拿上雨伞。','A preschool child with short black hair in yellow raincoat and red rain boots holds a small teal umbrella.'),('I jump in a puddle.','我跳进一个小水坑。','A preschool child with short black hair in yellow raincoat and red rain boots joyfully splashes in a shallow puddle holding a teal umbrella.'),('The rain stops at last.','雨终于停了。','A preschool child in yellow raincoat and red boots lowers a closed teal umbrella as sunlight comes out after rain.'),('I see a rainbow.','我看到一道彩虹。','A preschool child in yellow raincoat and red boots looks at a bright rainbow above a green garden.')]),
('time-for-bed','A','Time for Bed','晚安，好梦','#b8bad5',[
('I put my toys away.','我收好玩具。','A preschool child with short black hair in pale blue star pajamas puts wooden toys in a basket, warm evening light.'),('I take a warm bath.','我洗个温暖的澡。','A cheerful preschool child with short black hair takes a bath, completely covered below shoulders by dense bubbles, modest child-safe scene.'),('I put on my pajamas.','我穿上睡衣。','A preschool child with short black hair now fully dressed in pale blue star pajamas stands smiling by the bed.'),('I read with my dad.','我和爸爸一起读书。','A preschool child in pale blue star pajamas reads a picture book with a father in navy cardigan in a cozy bedroom.'),('I hug my teddy bear.','我抱抱我的泰迪熊。','A preschool child in pale blue star pajamas hugs a honey brown teddy bear under a cream quilt.'),('I close my sleepy eyes.','我闭上困倦的眼睛。','A preschool child in pale blue star pajamas sleeps peacefully under a cream quilt, honey brown teddy bear beside them, gentle moonlight.')])]
books=[]; prompts=[]
style='Use case: illustration-story. One finished square children\'s picture-book illustration for ages 3-6. Premium charming 3D animated-film render, rounded toy-like forms, tactile soft materials, warm gentle lighting, clean readable composition, rich but gentle colors. NO text, letters, logos, watermark, collage, or borders. '
for order,(bid,level,title,subtitle,color,lines) in enumerate(rows):
    pages=[]
    for i,(en,zh,scene) in enumerate(lines,1):
        path=f'/books/{bid}/page-{i:02}.png'
        pages.append(dict(id=f'{bid}-{i}',english=en,chinese=zh,image=path,alt=scene,audio=dict(kind='file',src=f'/audio/{bid}/page-{i:02}.wav')))
        prompts.append(dict(id=f'{bid}-{i}',path='public'+path,prompt=style+scene))
    cover=f'/books/{bid}/cover.png'
    prompts.append(dict(id=f'{bid}-cover',path='public'+cover,prompt=style+f'Cover artwork for an original early reader about {subtitle} ({title}). No written title; title will be added in website HTML. Create a cohesive appealing scene showing these motifs: '+ ' '.join(s for _,_,s in lines[:3])+' Main subject large and centered, cozy storybook atmosphere.'))
    books.append(dict(id=bid,level=level,title=title,subtitle=subtitle,cover=cover,tags=[subtitle],order=order,color=color,pages=pages))
(root/'src/content/books').mkdir(parents=True,exist_ok=True)
for b in books:(root/f'src/content/books/{b["id"]}.json').write_text(json.dumps(b,ensure_ascii=False,indent=2),encoding='utf-8')
(root/'src/content/catalog.ts').write_text("import type { Book } from './types';\n"+'\n'.join(f"import b{i} from './books/{b['id']}.json';" for i,b in enumerate(books))+f"\nexport const books = [{','.join(f'b{i}' for i in range(16))}] as Book[];\nexport const getBook = (id:string) => books.find(book => book.id === id);\n",encoding='utf-8')
(root/'docs/content').mkdir(parents=True,exist_ok=True)
(root/'docs/content/image-prompts.json').write_text(json.dumps(prompts,ensure_ascii=False,indent=2),encoding='utf-8')
print('Created 16 books / 96 pages / 112 image prompts')
